/******************************************************************************
 * Copyright © 2014-2019 The SuperNET Developers.                             *
 *                                                                            *
 * See the AUTHORS, DEVELOPER-AGREEMENT and LICENSE files at                  *
 * the top-level directory of this distribution for the individual copyright  *
 * holder information and the developer policies on copyright and licensing.  *
 *                                                                            *
 * Unless otherwise agreed in a custom licensing agreement, no part of the    *
 * SuperNET software, including this file may be copied, modified, propagated *
 * or distributed except according to the terms contained in the LICENSE file *
 *                                                                            *
 * Removal or modification of this copyright notice is prohibited.            *
 *                                                                            *
 ******************************************************************************/

#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0xfd,0x87,0xd8,0x7e,0xeb,0x43,0x90,0x0a,0x41,0x39,0x0d,0x41,0x60,0x12,0x2c,0xbd}, 8770},
    {{0xfd,0x87,0xd8,0x7e,0xeb,0x43,0x90,0x0a,0x41,0x39,0x0d,0xb8,0x38,0x11,0x22,0xf1}, 8770},
    {{0xfd,0x87,0xd8,0x7e,0xeb,0x43,0x90,0x0a,0x41,0x39,0x0d,0x32,0x7c,0x9f,0x1e,0x3a}, 8770},
    {{0xfd,0x87,0xd8,0x7e,0xeb,0x43,0x90,0x0a,0x41,0x39,0x0d,0x1b,0x01,0xa9,0x38,0x79}, 8770},
    {{0xfd,0x87,0xd8,0x7e,0xeb,0x43,0x90,0x0a,0x41,0x39,0x0d,0x5f,0x25,0x6f,0x56,0x94}, 8770},
    {{0xfd,0x87,0xd8,0x7e,0xeb,0x43,0x90,0x0a,0x41,0x39,0x0d,0x34,0x81,0xcd,0x6a,0x65}, 8770}
};

static SeedSpec6 pnSeed6_test[] = {
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
